first commit
galyastefany/parcel-final11 pull request #1
Opened 2024-04-15 10:25 UTC by galyastefany

2024-04-15 13:30 UTC, ivannizh reviewed
Привет! Хороший докер файл, работа принята!

2024-05-06 16:10 UTC, dirtymew requested changes
Привет Галина

нужно немного доделать задание

2024-05-06 16:10 UTC, dirtymew commented on .github/workflows/push.yaml
> +      - name: Vet
сначала линтеры потом тесты

2024-05-06 16:10 UTC, dirtymew commented on .github/workflows/push.yaml
> +    container: golang:1.22
в go mod
go 1.22.0  а в докере golang:1.22.2

лучше все к одной версии свести

2024-05-06 16:10 UTC, dirtymew commented on .github/workflows/push.yaml
> +          go vet ./...
не хватает этапа публикации на dockerhub по git tag-у

нужно его добавить и проверить что он отрабатывает и образ публикуется

2024-05-06 16:38 UTC, galyastefany commented on .github/workflows/push.yaml
> +    container: golang:1.22
Это не тот коммит...я сегодня переделала, 6 часов назад. Файл со всеми правками на 47 строк

2024-05-06 16:40 UTC, galyastefany commented on .github/workflows/push.yaml
> +    container: golang:1.22
[finish push.yaml](https://github.com/galyastefany/parcel-final11/commit/f8f3a7b2fb72e7dd871e3c468f39b1cc508b58ff)
запуталась, почему коммит не виден

2024-05-06 16:55 UTC, closed without merging

2024-05-06 17:06 UTC, dirtymew commented on .github/workflows/push.yaml
> +    container: golang:1.22
ой зря @galyastefany  PR нужно до конца ревью открытым держать... история потеряется